# -*- coding: utf-8 -*-
"""OS Lab_Assignment2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1usB54PyU7EQtMi-iriWMik7q9BORSUic
"""

import multiprocessing
import time
import logging

# Name of the log file
LOG_FILE = "process_log.txt"

# -----------------------------
# Sub-Task 1: Initialize logging
# -----------------------------
logging.basicConfig(
    filename=LOG_FILE,
    level=logging.INFO,
    format="%(asctime)s - %(processName)s - %(message)s",
    filemode="w"  # overwrite log file on each run
)

# Sub-Task 2: Define a function to simulate a process
# -------------------------------------------------
def system_process(task_name, duration_seconds):
    """
    Dummy function to simulate a system process.

    :param task_name: Name of the process/task
    :param duration_seconds: Time (in seconds) to sleep
    """
    logging.info(f"{task_name} started (sleep={duration_seconds}s)")
    time.sleep(duration_seconds)  # Simulate work
    logging.info(f"{task_name} ended")

    # Helper function to simulate system boot and shutdown
# -------------------------------------------------
def simulate_system_startup():
    print("System Starting...")
    logging.info("System boot sequence started")

# Sub-Task 3: Create at least two processes
# -----------------------------------------

process_specs = [
    ("Init-Process", 2),
    ("User-Process-1", 2),
    # Extra process (optional, shows more activity)
    ("Background-Process", 3)
]

processes = []

# Create and start processes
for name, duration in process_specs:
    p = multiprocessing.Process(
        target=system_process,
        args=(name, duration),
        name=name     # Sets processName in logs
    )
    logging.info(f"{name} created")
    processes.append(p)
    p.start()  # Start the process
    logging.info(f"{name} started (PID={p.pid})")

# Sub-Task 4: Ensure termination and joining
# -----------------------------------------
for p in processes:
    p.join()  # Wait until process finishes
    logging.info(f"{p.name} joined / terminated")

logging.info("System shutdown sequence completed")
print("System Shutdown.")

# Standard entry point
if __name__ == "__main__":
    simulate_system_startup()